version: '3'

services:
  app:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - phpmyadmin
    networks:
      - php

  mysql:
    image: mariadb:10.5
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=php-db
      - MYSQL_USER=php
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
    networks:
      - php

  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '9000:9000'
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - php

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - php

  composer:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - php

networks:
  php:
